project:
  type: website

website:
  title: "The popularity of songs"
  navbar:
    left:
      - href: index.qmd
        text: Using Supervised Machine Learning and Data Visualization

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

