project:
  type: website

website:
  title: "popular-spotify-tracks"
  navbar:
    left:
      - href: index.qmd
        text: Exploring the Popularity of Spotify Tracks

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

